### ISSUE TITLE
外部リポジトリからfetchしてきたyamlをconfiguration-pathに指定できない

### ISSUE THREAD

**Issue by k1z3** [abeyuya/actions-mention-to-slack#218]
いつもこちらのアクションを利用させてもらっています。ありがとうございます

organizationで利用する際、個人アカウントに依存しないようにしたく、GitHub Apps経由でprivate repositoryに保存された `mention-to-slack.yml` を読み込むようにして複数のリポジトリで `mention-to-slack.yml` を共有できるようにしたいと考えています

現在リポジトリが4つあり、
1. SlackにリメンションしたいPrivateリポジトリ (複数)
2. GitHub Appsを呼び出すためのPublicリポジトリ
3. `mention-to-slack.yml`が保存されたPrivateリポジトリ
4. Slackに通知するためのアクションが保存されたPublicリポジトリ(当リポジトリのForkです)

1 の hook で workflow を起動し、2 を呼び出すことで、3に保存された`mention-to-slack.yml` をcheckoutによりコピーしてきます。完了した後、4 を起動しSlackに通知するような仕組みです

GitHub Appsを経由する理由としては、権限問題を回避してPrivateリポジトリの情報を取得するためです
https://caddi.tech/archives/3737 (こちらのページを参考にしています)

当リポジトリのアクションでは
```
uses: abeyuya/actions-mention-to-slack@v2
with:
    configuration-path: ***mention-to-slack.yml
```
のようにすると、メンション先が記述されたyamlファイルを指定できると理解しています

```
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3
      # Github appsを使用して caddijp/common-github-actions private リポジトリを .github/actions/common にチェックアウト
      - uses: org-repo/checkout-private-action@main
        with:
          app_id: ${{ secrets.CHECKOUT_PRIVATE_ACTION_APPS_ID }}
          secret_key: ${{ secrets.CHECKOUT_PRIVATE_ACTION_APPS_SECRET }}
          org: "org-repo"
          repo: "slack-notification"
          ref: "dev"
          dist: "./.github/actions/common"
      - name: Run
        uses: k1z3/actions-mention-to-slack@0.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_FOR_MENTION_DEV }}
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          bot-name: "Mention bot"
          run-id: ${{ github.run_id }}
          configuration-path: .github/actions/common/.github/actions/slack-to-mention/mention-to-slack.yml
```

アクション自体は最後まで正常に終了していることになっています

* * *

しかし、checkoutによって持ってきたファイルの場合は、以下のようなエラーがSlackに投稿されます (`k1z3/actions-mention-to-slack` は4のことで、当リポジトリのForkです)
:exclamation: An internal error occurred in mention-to-slack action)
(but action didn't fail as this action is not critical).
To solve the problem, please open an issue
```
HttpError: Not Found
    at /home/runner/work/_actions/k1z3/actions-mention-to-slack/0.1.3/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.loadFromGithubPath (/home/runner/work/_actions/k1z3/actions-mention-to-slack/0.1.3/src/modules/mappingConfig.ts:43:22)
    at main (/home/runner/work/_actions/k1z3/actions-mention-to-slack/0.1.3/src/main.ts:246:21)
```

`mention-to-slack.yml`ファイルについては、元々 1 のリポジトリに保存されている場合は、`configuration-path` を指定しても問題なく読み込めます

しかし、fetchしたyamlを直接指定したり `cat` して 1 のリポジトリのファイルに追記するような操作をすると、読み込めなくなってしまいます

`ls` 等で確認はしましたが、コピー自体は行われておりました

ちなみに存在しないパスを指定したとしても、このようなエラーになりました

* * *

もう少し単純なものにして検証も行いたいのですが、取り急ぎissueを立てさせていただきました

GH-Actions の知見が薄く申し訳ないですが、もし解決できる方法がありましたら教えていただけると嬉しいです

また、目的が達成できれば良いとも考えていますので、これ以外に良い方法を提案していただいても嬉しいです

よろしくお願いします
