### ISSUE TITLE
Creation of pull request review comments are triggered twice

### ISSUE THREAD

**Issue by seriwb** [abeyuya/actions-mention-to-slack#273]
Thank you for making a good application.

August 3rd library update includes a fix for groups. As a result it now triggers twice on pull request review comment creation.

- https://github.com/actions/toolkit/compare/%40actions/core%401.0.0...%40actions/core%401.1.0?diff=split#diff-f63fb32fca85d8e177d6400ce078818a4815b80ac7a3319b60d3507354890992
- https://docs.github.com/ja/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review

When I changed the trigger for `pull_request_review_comment` to just `edited` it worked as before, so I'll leave the information here.

```yml
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [edited]
```
